# Generated by Django 6.0.7 on 2026-08-02 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_remove_user_otp_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingemail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pending Email', 'verbose_name_plural': 'Pending Emails'},
        ),
        migrations.AlterField(
            model_name='pendingemail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_email', to=settings.AUTH_USER_MODEL),
        ),
    ]
