# Generated by Django 6.0.7 on 2026-07-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the expense amount.', max_digits=10)),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('SHOPPING', 'Shopping'), ('BILLS', 'Bills'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('TRAVEL', 'Travel'), ('MOBILE', 'Mobile'), ('SOFTWARE', 'Software'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'EasyPaisa'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('date', models.DateField(db_index=True, verbose_name='Expense Date')),
                ('note', models.TextField(blank=True, help_text='Optional note about this expense.')),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expense Records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='expense_exp_user_id_31bf86_idx'), models.Index(fields=['user', 'category'], name='expense_exp_user_id_f5b7f4_idx'), models.Index(fields=['user', 'payment_method'], name='expense_exp_user_id_2dcb45_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_amount_positive')],
            },
        ),
    ]
