# Generated by Django 6.0.7 on 2026-07-26 18:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='expense',
            new_name='expense_user_date_idx',
            old_name='expense_exp_user_id_31bf86_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expense_user_category_idx',
            old_name='expense_exp_user_id_f5b7f4_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expense_user_payment_idx',
            old_name='expense_exp_user_id_2dcb45_idx',
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the expense amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
    ]
