# Generated by Django 6.0.7 on 2026-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_rename_expense_exp_user_id_31bf86_idx_expense_user_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterModelTable(
            name='expense',
            table='expenses',
        ),
    ]
