# Generated by Django 6.0.7 on 2026-07-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=10)),
                ('title', models.CharField(help_text='Example: Monthly Salary, Netflix, House Rent', max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('income_category', models.CharField(blank=True, choices=[('SALARY', 'Salary'), ('FREELANCING', 'Freelancing'), ('BUSINESS', 'Business'), ('INVESTMENT', 'Investment'), ('GIFT', 'Gift'), ('OTHER', 'Other')], max_length=20)),
                ('expense_category', models.CharField(blank=True, choices=[('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('SHOPPING', 'Shopping'), ('BILLS', 'Bills'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('TRAVEL', 'Travel'), ('MOBILE', 'Mobile'), ('SOFTWARE', 'Software'), ('OTHER', 'Other')], max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('DEBIT_CARD', 'Debit Card'), ('CREDIT_CARD', 'Credit Card'), ('JAZZCASH', 'JazzCash'), ('EASYPAISA', 'EasyPaisa'), ('OTHER', 'Other')], max_length=20)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('next_run', models.DateField(db_index=True)),
                ('last_generated_date', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurring Transaction',
                'verbose_name_plural': 'Recurring Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'next_run', 'is_active'], name='recurring_r_user_id_10317c_idx')],
            },
        ),
    ]
