# Generated by Django 6.0.7 on 2026-07-27 17:30

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recurringtransaction',
            new_name='recurring_user_next_run_is_active_idx',
            old_name='recurring_r_user_id_10317c_idx',
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('YEARLY', 'Yearly')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'transaction_type'], name='recurring_user_transaction_type_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'frequency'], name='recurring_user_frequency_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['user', 'is_active'], name='recurring_user_is_active_idx'),
        ),
        migrations.AddIndex(
            model_name='recurringtransaction',
            index=models.Index(fields=['is_active', 'next_run'], name='recurring_scheduler_idx'),
        ),
        migrations.AddConstraint(
            model_name='recurringtransaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('income_category__gt', ''), ('transaction_type', 'INCOME')), models.Q(('expense_category__gt', ''), ('payment_method__gt', ''), ('transaction_type', 'EXPENSE')), _connector='OR'), name='valid_recurring_transaction'),
        ),
    ]
