# Generated by Django 6.0.7 on 2026-07-27 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0002_rename_recurring_r_user_id_10317c_idx_recurring_user_next_run_is_active_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='recurringtransaction',
            new_name='recurring_user_next_idx',
            old_name='recurring_user_next_run_is_active_idx',
        ),
        migrations.RenameIndex(
            model_name='recurringtransaction',
            new_name='recurring_user_transaction_idx',
            old_name='recurring_user_transaction_type_idx',
        ),
    ]
