# Generated by Django 6.0.7 on 2026-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0003_rename_recurring_user_next_run_is_active_idx_recurring_user_next_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringtransaction',
            name='note',
            field=models.TextField(blank=True, help_text='Optional note about this recurring transaction.'),
        ),
        migrations.AlterField(
            model_name='recurringtransaction',
            name='title',
            field=models.CharField(help_text='Example: Monthly Salary, Netflix, House Rent', max_length=255),
        ),
        migrations.AlterModelTable(
            name='recurringtransaction',
            table='recurring_transactions',
        ),
    ]
