# Generated by Django 6.0.7 on 2026-07-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Enter the income amount.', max_digits=12)),
                ('category', models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCING', 'Freelancing'), ('BUSINESS', 'Business'), ('INVESTMENT', 'Investment'), ('GIFT', 'Gift'), ('OTHER', 'Other')], db_index=True, default='OTHER', max_length=20)),
                ('date', models.DateField(db_index=True, verbose_name='Income Date')),
                ('note', models.TextField(blank=True, help_text='Optional notes about this income.')),
                ('is_recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Income Records',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='income_inco_user_id_f74de7_idx'), models.Index(fields=['user', 'category'], name='income_inco_user_id_1110b8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='income_amount_positive')],
            },
        ),
    ]
