# Generated by Django 6.0.7 on 2026-07-25 17:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='income',
            new_name='income_user_date_idx',
            old_name='income_inco_user_id_f74de7_idx',
        ),
        migrations.RenameIndex(
            model_name='income',
            new_name='income_user_category_idx',
            old_name='income_inco_user_id_1110b8_idx',
        ),
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Enter the income amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
    ]
