# Generated by Django 6.0.7 on 2026-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_rename_income_inco_user_id_f74de7_idx_income_user_date_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='category',
            field=models.CharField(choices=[('SALARY', 'Salary'), ('FREELANCING', 'Freelancing'), ('BUSINESS', 'Business'), ('INVESTMENT', 'Investment'), ('GIFT', 'Gift'), ('OTHER', 'Other')], db_index=True, max_length=20),
        ),
    ]
