# Generated by Django 6.0.7 on 2026-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_income_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterModelTable(
            name='income',
            table='incomes',
        ),
    ]
