# Generated by Django 6.0.7 on 2026-07-20 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORT', 'Transport'), ('SHOPPING', 'Shopping'), ('BILLS', 'Bills'), ('ENTERTAINMENT', 'Entertainment'), ('HEALTH', 'Health'), ('EDUCATION', 'Education'), ('TRAVEL', 'Travel'), ('MOBILE', 'Mobile'), ('SOFTWARE', 'Software'), ('OTHER', 'Other')], db_index=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Monthly budget amount.', max_digits=12)),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.PositiveIntegerField(db_index=True, default=2026)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
                'ordering': ['-year', '-month', '-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='budgets_bud_user_id_c09b69_idx'), models.Index(fields=['user', 'year'], name='budgets_bud_user_id_85699b_idx'), models.Index(fields=['user', 'year', 'month'], name='budgets_bud_user_id_39ca25_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'category', 'month', 'year'), name='unique_user_category_month_year_budget'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='budget_amount_gt_zero')],
            },
        ),
    ]
