# Generated by Django 6.0.7 on 2026-07-26 18:06

import budgets.utils
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='budget',
            new_name='budget_user_category_idx',
            old_name='budgets_bud_user_id_c09b69_idx',
        ),
        migrations.RenameIndex(
            model_name='budget',
            new_name='budget_user_year_idx',
            old_name='budgets_bud_user_id_85699b_idx',
        ),
        migrations.RenameIndex(
            model_name='budget',
            new_name='budget_user_year_month__idx',
            old_name='budgets_bud_user_id_39ca25_idx',
        ),
        migrations.AlterField(
            model_name='budget',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Monthly budget amount.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.PositiveIntegerField(db_index=True, default=budgets.utils.current_year),
        ),
    ]
