# Generated by Django 6.0.7 on 2026-07-28 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_rename_budgets_bud_user_id_c09b69_idx_budget_user_category_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='budget',
            table='budgets',
        ),
    ]
