# Generated by Django 6.0.7 on 2026-07-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('BUDGET', 'Budget'), ('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('RECURRING', 'Recurring'), ('REMINDER', 'Reminder'), ('SYSTEM', 'System')], default='SYSTEM', max_length=20),
        ),
        migrations.AlterModelTable(
            name='notification',
            table='notifications',
        ),
    ]
